### ISSUE TITLE
enable iSCSI in kernel

### ISSUE THREAD

**Issue by sgoudelis** [radxa/debos-radxa#12]
Please enable iSCSI in the kernel in the next release.

```
Device Drivers  --->
  SCSI device support  --->
     <*> SCSI disk support
     [*] SCSI low-level drivers  --->
       <*> iSCSI Initiator over TCP/IP
         SCSI Transports --->
       {M} iSCSI Transport Attributes
```

**Comment by sgoudelis** [comment]
Can I enable it and build the image myself locally ?

**Comment by sgoudelis** [comment]
Nevermind, I found the build instructions here: https://wiki.radxa.com/Rock3/dev/Debian

It would be a good idea if iSCSI was included in future releases.

**Comment by StephenInVamrs** [comment]
{M} iSCSI Transport Attributes is already added.

 <*> iSCSI Initiator over TCP/IP will be added the the next release.

What other options do you think are needed for iSCSI?

**Comment by sgoudelis** [comment]
Thank you. The settings above are enough to get the iscsid started

**Comment by StephenInVamrs** [comment]
iSCSI is enabled in the latest kernel packages (4.19.193-31).

**Comment by sgoudelis** [comment]
Thank you very much
