### ISSUE TITLE
Rock Pi 4B with 5 inch Radxa LCD and modern kernel

### ISSUE THREAD

**Issue by mcartmel** [radxa/debos-radxa#13]
Hi, I have a Rock Pi 4B with 5 inch Radxa LCD attached to it and I have been able to enable output and a desktop using the instructions for the Debian and Ubuntu images. However, these images are based on kernel 4.4.

Are there any plans to update to a newer kernel version (say 5.10), with support for the MIPI display?

**Comment by StephenInVamrs** [comment]
Yes. It's our plan. We are moving to Linux 5.10 for ROCK Pi 4.

**Comment by RadxaYuntian** [comment]
4B image is already building with 5.10 now.
