### ISSUE TITLE
build ubuntu server image error

### ISSUE THREAD

**Issue by darkgirl** [radxa/debos-radxa#19]
Hi,
I am building ubuntu server image on Ubuntu18.04
After running 
`
./build.sh -c rk3399 -b rockpi-4b -m ubuntu -d focal -v server -a arm64 -f gpt
`
I got thoese error message

`
2022/05/21 03:45:52 error creating fakemachine: kvm backend not supported: open /dev/kvm: no such file or directory, uml backend not supported: user-mode-linux not installed
2022/05/21 03:45:52 fakemachine not supported, running on the host!
`
AND
`
2022/05/21 03:51:13 apt clean | Failed to stat /dev/disk: No such file or directory
2022/05/21 03:51:13 apt clean | Attempted to remove disk file system under "/run/systemd/nspawn/propagate/root", and we can't allow that.
2022/05/21 03:51:13 Action `debootstrap` failed at stage Run, error: exit status 1
2022/05/21 03:51:13 >>> Starting a debug shell
`

After running 
`
apt install user-mode-linux libslirp-helper
`
then I build the build ubuntu server image successfully.

**Comment by jack-ma** [comment]
Thanks, updated the README.

**Comment by darkgirl** [comment]
> Thanks, updated the README.

I am sorry. I did not say it clearly.
`
apt install user-mode-linux libslirp-helper
`
This command is added to "debos-radxa/docker/Dockerfile".
When I was building ubuntu server image, I found another issue, the error said that there is no enough space of my /dev/shm partition, so I have to the following command before running build.sh
`
mount -o remount,rw,nosuid,dev,exec,relatime,size=4G /dev/shm
`
But I am not sure if it is caused by my own mistake. If you need more specific details, I can help.

Thank you.

**Comment by jack-ma** [comment]
@darkgirl  PR is welcomed :-)
