### ISSUE TITLE
Hi, will this tool compile kernel from source code?

### ISSUE THREAD

**Issue by TurnOffNOD** [radxa/debos-radxa#24]
Hi, will this tool compile kernel from source code? Or it will pull a compiled kernel from some location? Can I change kernel parameter when making image with this tool?

**Comment by RadxaYuntian** [comment]
This tool only build image from pre-complied packages. To build kernel, please visit your device's page on https://wiki.radxa.com, which should contain necessary guide to help you build kernel for your device.

If you are looking to have some scripts to do it for you, please take a look at https://github.com/radxa/build and (WIP) https://github.com/radxa-repo/lbuild.
