### ISSUE TITLE
ROCK 5B 是否可以提供bullseye server版本镜像

### ISSUE THREAD

**Issue by kylinfedora** [radxa/debos-radxa#27]
ROCK 5B 是否可以提供bullseye server版本镜像

**Comment by dominch** [comment]
Yet again #9

**Comment by RadxaStephen** [comment]
ROCK 5B Debian11 server 在这里。

https://github.com/radxa-build/rock-5b/releases/download/20221125-1014/rock-5b_debian_bullseye_cli.img.xz

**Comment by dominch** [comment]
> ROCK 5B Debian11 server 在这里。（用户名/密码：radxa/radxa）

Great! :)
