### ISSUE TITLE
Rock Pi  4C Plus 使用新板本Debian 11 bullseye 镜像WIFI无法连接

### ISSUE THREAD

**Issue by yoyojacky** [radxa/debos-radxa#29]
操作系统版本： Debian GNU/Linux 11 ( bullseye)
内核版本： Linux rockpi-4cplus 4.4.194-4-rk3399-rockchip-g5fbf835e0ac4 aarch64 GNU/Linux
问题：
在尝试使用wpa_passphrase 配置wpa_supplicant.conf 配置文件并尝试进行连接一直失败。
详细说明：https://forum.radxa.com/t/rock-4c-plus-wifi-can-not-connect/11612/2

**Comment by RadxaStephen** [comment]
Use command.

```
sudo nmcli dev wifi connect ”<ssid>” password “<password>”
```
