### ISSUE TITLE
I can't install kubernetes because module br_netfilter not found in ubuntu server 20.04

### ISSUE THREAD

**Issue by jikunchong** [radxa/debos-radxa#32]
system image: rock-5b-ubuntu-focal-server-arm64-20220930-1451-gpt.img.xz
ubuntu server version: 20.04.5

step docs:  https://kubesphere.io/docs/v3.3/quick-start/all-in-one-on-linux/
installer: [kubekey v2.2.2](https://github.com/kubesphere/kubekey/tree/v2.2.2)

```shell
./kk create cluster --with-kubernetes v1.23.8
```

```shell
22:44:25 CST [InitKubernetesModule] Init cluster using kubeadm
22:44:26 CST stdout: [rock-5b]
W1015 22:44:25.913328   13561 utils.go:69] The recommended value for "clusterDNS" in "KubeletConfiguration" is: [10.233.0.10]; the provided value is: [169.254.25.10]
[init] Using Kubernetes version: v1.23.8
[preflight] Running pre-flight checks
        [WARNING SystemVerification]: missing optional cgroups: hugetlb
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

```

```shell
modprobe br_netfilter
```

```shell
modprobe: FATAL: Module br_netfilter not found in directory /lib/modules/5.10.66-24-rockchip-gcb09ad15af75
```

**Comment by ihexon** [comment]
origin vendor kernel compile without `br_netfilter` and `nf_table` you need recompile the vendor kernel for include those modules.

You can install the kernel package I maintain, which ready in production env

**Comment by jikunchong** [comment]
fixed.
We look forward to the release of the next image version.
https://github.com/radxa/debos-radxa/releases

Temporary available version:
https://github.com/rockchip-linux/kernel/issues/273#issuecomment-1295914501
