### ISSUE TITLE
Ubuntu Does Not Have Package user-mode-linux

### ISSUE THREAD

**Issue by stvhay** [radxa/debos-radxa#47]
The instructions say to install user-mode-linux on an Ubuntu host machine. This package does not exist on Ubuntu.

https://packages.ubuntu.com/search?keywords=user-mode-linux&searchon=names

Since the build actually seems to happen in Docker, I am wondering maybe this dependency is unneeded?

**Comment by RadxaStephen** [comment]
Sorry for misleading you.

The user-mode-linux is not needed on Ubuntu PC.
I just correct the README.md

**Comment by stvhay** [comment]
Thank you. I've confirmed this by completing a build on an amd64 machine.
