### ISSUE TITLE
Newer Zero images get stuck in a boot loop

### ISSUE THREAD

**Issue by curious-futurist** [radxa/debos-radxa#49]
Hi. I know that according to the change logs, there haven't been many (or any) changes to the Zero image for a while. But I just wanted to note that images newer than 20220801 (at least the few recent ones that I had time to check) don't boot and get stuck in an infinite boot loop. At least in case of the 2GB version.

I'm signaling here because, what's especially annoying, everywhere else I get the response to just use Armbian.
Well, no. Armbian is not suitable for me, but it seems that it's incomprehensible to the people on the forum and the discord channel.

**Comment by canton09** [comment]
me too！！

**Comment by nascs** [comment]
debos is no longer in maintenance, you can get image from https://github.com/radxa-build .

**Comment by curious-futurist** [comment]
> debos is no longer in maintenance, you can get image from https://github.com/radxa-build .

Thanks for the info, makes sense.
But then why are images still actively released in debos?

I also meant to ask why the official wiki redirects to debos, as it was the case when I first got to work with the board, but I see that it's already been changed to build.

**Comment by nascs** [comment]
Radxa-build is still a little imperfect, but when the testing is all done, the wiki page will change to Radxa-build.
