### ISSUE TITLE
Add more xfce and server versions 

### ISSUE THREAD

**Issue by dominch** [radxa/debos-radxa#9]
Can You please add more system images? 
- with xfce 
- cli only 
More distros: 
- debian bullseye 

I would like to use debian bullseye server image and only older buster and with xfce is available now.

**Comment by StephenInVamrs** [comment]
For which board?

**Comment by dominch** [comment]
I'd like to use it with rock3a and later with upcoming rock5, 
I think more people will be interested with desktop ubuntu and plain/cli debian. 
Are there any chances for current bullseye?

**Comment by ElishaBentzi** [comment]
Thanks, please add manjaro to rock3a

**Comment by jack-ma** [comment]
@ElishaBentzi you can find the manjaro build for 3a here:

https://github.com/manjaro-arm/rock3a-images

**Comment by StephenInVamrs** [comment]
For Manjaro for ROCK 3A, please visit here. https://github.com/manjaro-arm/rock3a-images/releases

**Comment by dominch** [comment]
This issue is still unresolved, manjaro is in different repo but still no server debian with no gui :(

**Comment by StuartIanNaylor** [comment]
cli only as a base for all distro's should be a norm.

**Comment by RadxaStephen** [comment]
Hi, you can find ROCK 5B Debian11 server image here. https://github.com/radxa-build/rock-5b/releases

Like https://github.com/radxa-build/rock-5b/releases/download/20221125-1014/rock-5b_debian_bullseye_cli.img.xz

Basic information:

* user/password: radxa/radxa

When you have issues with that, please raise one issue here. https://github.com/radxa-repo/rbuild/issues

**Comment by StuartIanNaylor** [comment]
Is every now on rbuild Stephen?
